### PR TITLE
Add listeners to gd.py's memory module

### PR DESCRIPTION
**Pull request by spookybear0**
# Not done

### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new class, method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation update, README, etc.)

### CODE REVIEW

**Comment by nekitdev** [comment]
Overall sounds like a good idea! Though, I think we should rather implement listeners via having daemon thread listening.

**Comment by spookybear0** [comment]
Good idea, im not sure how to do that, so maybe you can do that part.

**Comment by nekitdev** [comment]
That would require overall rewamp and rewrite of this code, to be honest.

**Comment by spookybear0** [comment]
Oh. Are there any benefits to doing that?

**Comment by nekitdev** [comment]
Threading will allow us to listen in non-blocking way, to start with.

**Comment by spookybear0** [comment]
I will start working on threading. (also, should I use threading or multithreading package)

**Comment by nekitdev** [comment]
``threading`` is the builtin one.

**Comment by spookybear0** [comment]
I will use threading then, as it is one less dependency.

**Comment by nekitdev** [comment]
Closing this due to inactivity and lack of clear implementation.

**Pull request closed without merging**
