### PR TITLE
Use TYPE_CHECKING blocks

### PR DESCRIPTION
**Pull request by johnslavik**
Used the following command sequence:
`ruff check gd/ --select=TCH --unsafe-fixes --fix`
`ruff check gd/ --select=I001,F401 --fix`

No regression observed from `mypy gd/ --strict`.

### CODE REVIEW

**Comment by johnslavik** [comment]
Looks like my line length setting was applied. Should I change the editor config or tweak the `pyproject.toml` settings?

**Comment by nekitdev** [comment]
Let's try to keep line length at `100` max.

**Comment by johnslavik** [comment]
> Let's try to keep line length at `100` max.

I wasn't questioning the 100 max line length; I was asking if I should change the editor config or tweak the `pyproject.toml` settings to reach Ruff as well as the IDEs that can read the `.editorconfig` file, which currently doesn't specify the max line length.

**Comment by johnslavik** [comment]
Guess I will build on the result of resolving #102. Please wait for the relevant PR to come.

**Comment by nekitdev** [comment]
Alright!

**Pull request merged**
